sulu_product:
    resource: "@SuluProductBundle/Resources/config/routing_api.yml"
    prefix: /api

product_list:
    pattern: /template/product/list.html
    defaults: { _controller: SuluProductBundle:Template:productList }

product_import:
    pattern: /template/product/import.html
    defaults: { _controller: SuluProductBundle:Template:productImport }
