sulu_product_base.products:
    type: rest
    resource: Sulu\Bundle\ProductBundle\Controller\ProductController

sulu_product_base.attributes:
    type: rest
    resource: Sulu\Bundle\ProductBundle\Controller\AttributeController

sulu_product_base.attribute_values:
    type: rest
    resource: Sulu\Bundle\ProductBundle\Controller\ValuesController
    parent: sulu_product_base.attributes
