product_list:
    pattern: /template/product/list.html
    defaults: { _controller: SuluProductBundle:Template:productList }

product_form:
    pattern: /template/product/form.html
    defaults: { _controller: SuluProductBundle:Template:productForm }

product_import:
    pattern: /template/product/import.html
    defaults: { _controller: SuluProductBundle:Template:productImport }

attribute_list:
    pattern: /template/attribute/list.html
    defaults: { _controller: SuluProductBundle:Template:attributeList }

attribute_form:
    pattern: /template/attribute/form.html
    defaults: { _controller: SuluProductBundle:Template:attributeForm }
