sulu_product.navigation:
    path: /navigation/product
    defaults: { _controller: SuluProductBundle:Navigation:product }

sulu_product.product_list:
    pattern: /template/product/list.html
    defaults: { _controller: SuluProductBundle:Template:productList }

sulu_product.product_form:
    pattern: /template/product/form.html
    defaults: { _controller: SuluProductBundle:Template:productForm }

sulu_product.product_import:
    pattern: /template/product/import.html
    defaults: { _controller: SuluProductBundle:Template:productImport }
