parameters:
    sulu_product.admin.class: Sulu\Bundle\ProductBundle\Admin\SuluProductAdmin
    sulu_product.product_repository.class: Sulu\Bundle\ProductBundle\Entity\ProductRepository
    sulu_product.product_manager.class: Sulu\Bundle\ProductBundle\Product\ProductManager

services:
    sulu_product.admin:
        class: %sulu_product.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }

    sulu_product.product_repository:
        class: %sulu_product.product_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["SuluProductBundle:Product"]

    sulu_product.product_manager:
        class: %sulu_product.product_manager.class%
        arguments:
            - "@sulu_product.product_repository"
            - "@doctrine.orm.entity_manager"
