parameters:
    sulu_product.admin.class: Sulu\Bundle\ProductBundle\Admin\SuluProductAdmin

services:
    sulu_product.admin:
        class: %sulu_product.admin.class%
        arguments: [%sulu_admin.name%]
        tags:
        - { name: sulu.admin }
